/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.applet.AudioClip;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ADALBERTO
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        // Añadir la imagen en el boton y ajustar su tamaño

//        Boton_Play.setIcon(setIcono("/imagenes/pngwing.com.png", Boton_Play));

        // Animacion de los botones al dar click
        Boton_Play.setPressedIcon(setIconoPresionado("/imagenes/PlayButton.png", Boton_Play, 10, 10));
        BtInformation.setPressedIcon(setIconoPresionado("/imagenes/InfoButton.png", Boton_Play, 10, 10));
        BtOpciones.setPressedIcon(setIconoPresionado("/imagenes/ConfigButton.png", Boton_Play, 10, 10));
        BtMusica.setPressedIcon(setIconoPresionado("/imagenes/MusicButton.png", Boton_Play, 10, 10));
        BtSalir.setPressedIcon(setIconoPresionado("/imagenes/ExitButton3.png", Boton_Play, 2, 2));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtSalir = new javax.swing.JButton();
        Boton_Play = new javax.swing.JButton();
        BtInformation = new javax.swing.JButton();
        BtOpciones = new javax.swing.JButton();
        BtMusica = new javax.swing.JButton();
        LabelBrillitos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Imagen_Inicio = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MapleLeaves.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 280, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WaterMist.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -30, 480, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LeavesFallingGif.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 0, 260, 170));

        BtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ExitButton3.png"))); // NOI18N
        BtSalir.setBorderPainted(false);
        BtSalir.setContentAreaFilled(false);
        BtSalir.setFocusPainted(false);
        BtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Boton_Play.setBackground(new java.awt.Color(102, 102, 102));
        Boton_Play.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlayButton.png"))); // NOI18N
        Boton_Play.setToolTipText("");
        Boton_Play.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Boton_Play.setBorderPainted(false);
        Boton_Play.setContentAreaFilled(false);
        Boton_Play.setFocusPainted(false);
        Boton_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PlayActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 350, 120));

        BtInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InfoButton.png"))); // NOI18N
        BtInformation.setBorderPainted(false);
        BtInformation.setContentAreaFilled(false);
        BtInformation.setFocusPainted(false);
        BtInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInformationActionPerformed(evt);
            }
        });
        jPanel1.add(BtInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 350, 120));

        BtOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConfigButton.png"))); // NOI18N
        BtOpciones.setBorderPainted(false);
        BtOpciones.setContentAreaFilled(false);
        BtOpciones.setFocusPainted(false);
        BtOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtOpcionesActionPerformed(evt);
            }
        });
        jPanel1.add(BtOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 350, 130));

        BtMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MusicButton.png"))); // NOI18N
        BtMusica.setBorderPainted(false);
        BtMusica.setContentAreaFilled(false);
        BtMusica.setFocusPainted(false);
        BtMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMusicaActionPerformed(evt);
            }
        });
        jPanel1.add(BtMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 350, 120));

        LabelBrillitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sparkle.gif"))); // NOI18N
        jPanel1.add(LabelBrillitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 330, 280));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Titulo Juego.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 750, 190));

        Imagen_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio Imagen.jpg"))); // NOI18N
        jPanel1.add(Imagen_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -7, 1110, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_PlayActionPerformed

    private void BtInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInformationActionPerformed
        this.setVisible(false);
        Information inf = new Information();

        inf.setVisible(true);
    }//GEN-LAST:event_BtInformationActionPerformed

    private void BtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirActionPerformed
        System.exit(WIDTH);

    }//GEN-LAST:event_BtSalirActionPerformed

    private void BtOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtOpcionesActionPerformed
        this.setVisible(false);
        Menu_Opciones op = new Menu_Opciones();

        op.setVisible(true);
    }//GEN-LAST:event_BtOpcionesActionPerformed

    private void BtMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMusicaActionPerformed
        this.setVisible(false);
        Musica_Op mu = new Musica_Op();

        mu.setVisible(true);

    }//GEN-LAST:event_BtMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Ajusatar la imagen en el boton 

//    public Icon setIcono(String url, JButton boton) {
//        ImageIcon icon = new ImageIcon(getClass().getResource(url));
//
//        int ancho = boton.getWidth();
//
//        int alto = boton.getHeight();
//
//        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
//
//        return icono;
//    }
    // Pequeña animacion al dar click en el boton 
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth() - ancho;
        int height = boton.getHeight() - altura;

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));

        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Play;
    private javax.swing.JButton BtInformation;
    private javax.swing.JButton BtMusica;
    private javax.swing.JButton BtOpciones;
    private javax.swing.JButton BtSalir;
    private javax.swing.JLabel Imagen_Inicio;
    private javax.swing.JLabel LabelBrillitos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
