/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

/**
 *
 * @author HP
 */
public class Menu_Bienvenido extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Bienvenido
     */
    public Menu_Bienvenido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtGo = new javax.swing.JButton();
        BtInfo = new javax.swing.JButton();
        BtRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GoButtonBig.png"))); // NOI18N
        BtGo.setContentAreaFilled(false);
        BtGo.setFocusPainted(false);
        BtGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGoActionPerformed(evt);
            }
        });
        add(BtGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        BtInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/infoButton3.png"))); // NOI18N
        BtInfo.setBorderPainted(false);
        BtInfo.setContentAreaFilled(false);
        BtInfo.setFocusPainted(false);
        BtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInfoActionPerformed(evt);
            }
        });
        add(BtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        BtRegresar.setBackground(new java.awt.Color(102, 146, 52));
        BtRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GoBackButton.png"))); // NOI18N
        BtRegresar.setBorder(null);
        BtRegresar.setContentAreaFilled(false);
        BtRegresar.setFocusPainted(false);
        BtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegresarActionPerformed(evt);
            }
        });
        add(BtRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JungleMenuBienvenida.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtGoActionPerformed

    private void BtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtInfoActionPerformed

    private void BtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGo;
    private javax.swing.JButton BtInfo;
    private javax.swing.JButton BtRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
